### PR TITLE
Update calibration methods, add tests.

### PR DESCRIPTION
**Pull request by bas-rustenburg**
MBAR calibration currently not working because it depends on context in the initialization. Will fix this at another time.

### CODE REVIEW

**Comment by jchodera** [comment]
> MBAR calibration currently not working because it depends on context in the initialization

Can you elaborate?

**Comment by bas-rustenburg** [comment]
Sure. The calibration class that uses MBAR currently uses context as an argument in it's `__init__` function. However, since we now use a compound integrator, and generate a context using that integrator, we have to define the `Titration` object first before we have a context.

I may be able to move this so context isn't needed in `__init__`. I could potentially merge it into the other calibration class.

**Comment by bas-rustenburg** [comment]
Here is the test case that shows the issue:

https://github.com/choderalab/openmm-constph/blob/master/constph/tests/test_explicit.py#L132-L137

**Comment by jchodera** [comment]
Ah, so you just need to fix up the API.

Why not just replace `context` with `system`, and take an optional `platform` argument?

**Comment by bas-rustenburg** [comment]
For the sake of unifying the APIs, I think with a little bit of work, we can include an `mbar` option as an alternative to `eq9` and `eq12`, as opposed to fixing the MBAR class with a separate api. 

The one thing in which the classes fundamentally differ -- which will be the part that takes some work --is storing all the previous states. Right now `MBarCalibrationTitration` use this `adaptation_tracker` dictionary entry to keep track of all past samples. Its `__init__` requires the context because I need to extract the potential for the initial state. I would have to incorporate that into the `CalibrationTitration` code. 

It'll take some time, and for now it isn't high priority, since we can already use SAMS _on-line_. MBAR was just an interesting _at-line_ alternative, and we could just run MBAR _off-line_ if we wanted to. Not fixing this right now shouldn't hold up our development.

**Comment by bas-rustenburg** [comment]
Added reminder to #20.

**Comment by gregoryross** [comment]
You've probably already done this, but have you compared the free energies you get with SAMS with the free energies you get with MBAR? This is an important validation test for the SAMS code.

**Comment by bas-rustenburg** [comment]
@gregoryross Very qualitatively yes, they seemed to match up, but I'd like to set up a test suite/example set that proves this.

**Comment by bas-rustenburg** [comment]
Added reminder for that to #20.

**Pull request merged**
