### PR TITLE
Add benchmark files.

### PR DESCRIPTION
**Pull request by bas-rustenburg**
These are all the input files. Haven't run them all yet. 

A little heads up, this might take a while. LDHA has an ETA of  1 day, 22h in explicit solvent, to generate 5 ps of data. I'll try and get the small systems done first.

### CODE REVIEW

**Comment by bas-rustenburg** [comment]
Added the call graphs, showing number of calls on the edges, and inclusive cost in percentages.

**Comment by bas-rustenburg** [comment]
No results yet for LDHA benchmarks, as they are still running.

**Comment by bas-rustenburg** [comment]
Interestingly, looking at the main contributors to `update`.  
For implicit solvent: 
dhfr: `setExceptionParameters` 17%, `updateParametersInContext`, 7 %, `getState` 8%, `__eq__` 14%
abl: `setExceptionParameters` 15%,  `updateParametersInContext`.  6 %, `getState` 11%, `__eq__` 12%
For explicit:
dhfr: `setExceptionParameters` 12%, `updateParametersInContext`13 %, `getState` 9%, `__eq__` 9%
abl: `setExceptionParameters` 12%, `updateParametersInContext` 16 %, `getState` 9% `__eq__` 9%

`setExceptionParameters`. __eq__ and `updateParametersInContext`,  are called in `setTitrationState`,
wheras `getState` is called in `_compute_log_probability`. ` __eq__` comes from quantity.py

**Comment by jchodera** [comment]
We need to know how much time is spent in `integrate.step()` the constant pH code.

**Comment by bas-rustenburg** [comment]
See the summary. txt files:
abl-explicit:
0.003174 s/timestep                           0.087081 s/titration trial
abl-implicit:
0.001861 s/timestep                          0.072880 s/titration trial
dhfr-explicit:
0.002821 s/timestep                          0.078380 s/titration trial
dhfr-implicit
0.000796  s/timestep                          0.061490 s/titrationtrial

**Comment by bas-rustenburg** [comment]
Or, look at the percentages in the graphs.

**Comment by jchodera** [comment]
Is that timing per single `step(1)` timestep?  If so, can you convert that to how many timesteps would be needed to make `integrate.step(nsteps)` take just as long as the titration step?

**Comment by bas-rustenburg** [comment]
abl-explict : 27.453882 * 39 = 1071 

abl-implicit:  39.179890 * 39 = 1528

dhfr-explicit:   27.802282*  30 = 834

dhfr-implicit:  77.209022 * 30 = 2316

**Comment by jchodera** [comment]
Confused.  Shouldn't that be, for `abl-explicit`, (0.087081 s/titration) / (0.003174 s/timestep) = ~27 timesteps?

**Comment by bas-rustenburg** [comment]
But it runs multiple trials each step, so the entire titration update is * the number of trials. If you just want the ratio, its the first number in the multiplication step.

**Comment by jchodera** [comment]
OK!  So we're looking at the instantaneous protonation state change trials cost 30-80x as much as a single timestep for these systems?

**Comment by bas-rustenburg** [comment]
I'm not sure what the definition of "instantaneous" is in this context. Single residue updates cost 30-80x more, and we try as many trials as there are titratable residues, per 500 timesteps.

**Comment by jchodera** [comment]
"Instantaneous Mont Carlo", as distinguished from NCMC protonation state switches

**Comment by bas-rustenburg** [comment]
Will add ldha-explicit data at a later time.

**Pull request merged**
