### PR TITLE
Benchmark ncmc [WIP]

### PR DESCRIPTION
**Pull request by bas-rustenburg**
Have now merged in NCMC code. Will run new benchmarks.

### CODE REVIEW

**Comment by jchodera** [comment]
How is benchmarking coming along?

**Comment by bas-rustenburg** [comment]
Some data from running a single amino acid (asp). 
average MD step/NCMC step ratio: 0.1682319
average MD step/Update(1000 ncmc steps) ratio: 0.0001682 (1 attempt per update)

**Comment by jchodera** [comment]
> average MD step/NCMC step ratio: 0.1682319

That means the NCMC step is only 1/0.1682319 = 5.9x more expensive than the MD step?

> average MD step/Update(1000 ncmc steps) ratio: 0.0001682 (1 attempt per update)

I don't understand what this mean.

**Comment by bas-rustenburg** [comment]
That last number is the first one multiplied by the number of  number of steps per NCMC switching trial, I used 1000 in this case.

**Comment by bas-rustenburg** [comment]
To be complete: 

The second number is the total duration of the update step, assuming we'd need 1000 steps of NCMC. The first one is that number, divided by the number of time steps inside NCMC part (1000).

**Comment by bas-rustenburg** [comment]
Merging this so I can start restructuring parts of the repository.

**Pull request merged**
