### PR TITLE
[WIP] NCMC for explicit solvent constant-pH

### PR DESCRIPTION
**Pull request by jchodera**
Beginning changes discussed in #13.

- [x] Add an optional argument to `MonteCarloTitration` constructor called `maintainChargeNeutrality` to select whether water molecules should be replaced with ions to maintain charge neutrality.  
- [x] Monovalent cation/anion parameters would be optionally set with `cationName='Na+'` and `anionName='Cl-'` which specifies name of atom in `prmtop.topology` from which to take `(charge, sigma, epsilon)` parameters from when waters are converted into monovalent ions to maintain charge neutrality.  This would obviously only be used in explicit solvent.
- [x] Build a list of water molecules.
- [x] A class method `nsteps_per_trial` (optionally set during the `MonteCarloTitration` constructor) will control whether we are using instantaneous switching (0 steps) or NCMC (>= 1 steps).
- [ ] Each MC update attempt, the original positions and velocities will be cached, and we will use the integrator described in [this paper](http://threeplusone.com/Sivak2013a.pdf)---where the Hamiltonian switching updates happen in between the middle of the timestep---to integrate dynamics.  The NCMC criteria will be used to accept/reject the move, as in [the recent Roux paper](http://pubs.acs.org/doi/abs/10.1021/acs.jctc.5b00261).
- [ ] For now, I will assign a new momentum at the beginning of each NCMC switching iteration, but we can implement more clever approaches to avoid momentum reversal (e.g. those from Roux) later once we have benchmarking data.
- [ ] If `maintainChargeNeutrality=True` and there are waters in the system, we will convert waters to/from monovalent ions to maintain charge neutrality during the switching process.  We will only convert either waters or monovalent ions that have been converted from waters by the constant-pH facility---we will not modify any existing ions, since we can't easily convert those back into waters.  We will keep the hydrogen masses constant, but turn off the electrostatics on the hydrogens as waters are converted into ions.  Initially, we will just select waters or ions at random, but later, we may be able to select waters/ions based on electrostatics to increase acceptance probabilities.

### CODE REVIEW

**Comment by jchodera** [comment]
Surprisingly, the simple explicit solvent calibration examples actually change protonation state even with non-neutralizing instantaneous Monte Carlo.

**Comment by jchodera** [comment]
Obviously only partway through this, but I'm thinking about how best to handle the coupling with converting waters to/from monovalent ions.

We could obviously do this in multiple ways.  My prevailing ideas are:
* 1. If we are incrementing the charge in a manner that can be compensated by changing one of the monovalent ions we have introduced back into a water, we select this ion to be transmuted by to water.  This keeps the number of added ions to a minimum.  Simple, but maybe not so realistic or efficient.
* 2. Instead, we require the user to specify a counterion *concentration* if they want to use `maintainChargeNeutrality=True`.  We then compute an effective chemical potential for each ionic species and use this in a semigrand canonical scheme that goes in the acceptance probability.  Somewhat clever choices of whether to convert a water to a counterion or vice-versa will probably increase acceptance probabilities.

Any preferences?

**Comment by jchodera** [comment]
I should be able to wrap up this PR without the constant counterion concentration calibration part today.

I am working on the theory and calibration of the salt chemical potential as a function of salt concentration in a separate repo. For now we should be able to set the chemical potential to zero and limit our creation/deletion of cointerions to just maintaining charge neutrality.

**Comment by jchodera** [comment]
I've now added a basic NCMC implementation, but I am using a symmetric velocity Verlet protocol that is not as efficient as it could be because it doubles the number of force updates needed.  We can also improve the efficiency of multiple simultaneous protonation state updates, since each protonation state now currently calls `context.updateParametersInContext()` after being updated.

I'm also not yet randomizing velocities but flipping the velocity upon acceptance, since I think this will be more efficient.

I broke out the `__main__()` code from `constph.py` to `explicit-solvent-example.py`.

I still need to implement the charge neutrality maintenance scheme.

Some observations:
* `VVVRIntegrator` is much, much slower than `LangevinIntegrator` on the CPU platform:
* `LocalEnergyMinimizer` fails on the Tyr in explicit solvent system if the integrator tolerance is tighter than 1e-5.  This seems like an undesirable property.  We need tight integrator tolerance to avoid energy leakage during VVVR steps of systems with CCMA constraints, which has a habit of poor energy conservation when poor tolerances are used that lead to mistakenly high acceptance rates.

We can probably at least start to do some benchmarking at this stage.

**Comment by bas-rustenburg** [comment]
Great. Do you want to merge this, and implement the remaining stuff in a separate pull request? That way I can start benchmarking. I can also try implementing the remaining stuff, in case you don't get around to it.

I've already edited the benchmark code on a separate branch, and I've prepared some analysis tools. I'm waiting with the PR until this one is merged because it might not merge automatically.

**Comment by jchodera** [comment]
Sure, go for it.  At most, the optimizations will speed things up by a factor of two, and you can mimic this by replacing `VVVRIntegrator` with `VerletIntegrator` for benchmarking (ignoring the other changes for now).

**Comment by bas-rustenburg** [comment]
@jchodera : Running into an error with your example. Openmm version related maybe?

```pytb
Traceback (most recent call last):
  File "explicit-solvent-example.py", line 125, in <module>
    mc_titration = MonteCarloTitration(system, temperature, pH, prmtop, cpin_filename, integrator, debug=True, pressure=pressure, nsteps_per_trial=10)
  File "/home/bas/Repos/jchodera-openmm-constph/constph.py", line 167, in __init__
    self.compound_integrator = openmm.CompoundIntegrator()
AttributeError: module 'simtk.openmm' has no attribute 'CompoundIntegrator'
```

**Comment by bas-rustenburg** [comment]
My env
```yaml
name: constph
dependencies:
- alabaster=0.7.6=py35_0
- ambermini=15.0.4=1
- babel=2.1.1=py35_0
- boost=1.59.0=py35_1
- bzip2=1.0.6=0
- docutils=0.12=py35_0
- fftw3f=3.3.4=2
- hdf5=1.8.15.1=2
- jinja2=2.8=py35_0
- joblib=0.8.4=py35_0
- libgfortran=1.0=0
- libxml2=2.9.2=0
- libxslt=1.1.28=0
- lxml=3.5.0=py35_0
- markupsafe=0.23=py35_0
- mdtraj=1.5.1=np110py35_0
- nose=1.3.7=py35_0
- numexpr=2.4.6=np110py35_0
- numpy=1.10.2=py35_0
- numpydoc=0.5=py35_1
- openblas=0.2.14=3
- openmm=6.3.1=py35_0
- openmm-dev=7.0.0.dev0=py35_0
- openmmtools=0.7.5=py35_1
- openmoltools=0.6.9=py35_1
- openssl=1.0.2e=0
- pandas=0.17.1=np110py35_0
- parmed=2.0.5=py35_0
- pip=7.1.2=py35_0
- pygments=2.0.2=py35_0
- pymbar=3.0.0.beta2=np110py35_0
- pytables=3.2.2=np110py35_0
- python=3.5.1=0
- python-dateutil=2.4.2=py35_0
- pytz=2015.7=py35_0
- pyyaml=3.11=py35_1
- rdkit=2015.09.1=py35_1
- readline=6.2=2
- scipy=0.16.1=np110py35_0
- scripttest=1.3=py35_0
- setuptools=19.2=py35_0
- six=1.10.0=py35_0
- snowballstemmer=1.2.0=py35_0
- sphinx=1.3.1=py35_0
- sphinx_rtd_theme=0.1.7=py35_0
- sqlite=3.9.2=0
- tk=8.5.18=0
- wheel=0.26.0=py35_1
- xz=5.0.5=0
- yaml=0.1.6=0
- zlib=1.2.8=0
- pip:
  - bottle==0.12.9
  - cprofilev==1.0.7
  - progressbar2==3.5.1
  - snakeviz==0.4.0
  - sphinx-rtd-theme==0.1.7
  - tables==3.2.2
  - tornado==4.3
  - yappi==0.94
```

**Comment by jchodera** [comment]
You need openmm-dev instead of openmm

**Comment by bas-rustenburg** [comment]
I have dev installed. But I think openmmtools might install the regular openmm on top of the dev package.

**Comment by bas-rustenburg** [comment]
```
zsh 1904 [1]  (git)-[ncmc]-% conda install openmmtools
Fetching package metadata: ......
Solving package specifications: ..............................
Package plan for installation in environment /home/bas/miniconda3/envs/constph:

The following NEW packages will be INSTALLED:

    openmm: 6.3.1-py35_0

Proceed ([y]/n)?

```

**Comment by jchodera** [comment]
You have both `openmm` and `openmm-dev` installed:
```
- openmm=6.3.1=py35_0
- openmm-dev=7.0.0.dev0=py35_0
```

**Comment by jchodera** [comment]
You need to do the following *after* installing the dependencies:
```
conda remove --yes openmm
conda install --yes openmm-dev
```

**Comment by jchodera** [comment]
`conda` doesn't yet have a way to specify that one package conflicts with another, unfortunately.  This is the drawback of using separate `openmm` and `openmm-dev` packages rather than separate version numbers.  We just never found a way to get the separate version numbers to work correctly for dev packages, though it may be worth revisiting this (using version `0.0.0` or something).

**Comment by bas-rustenburg** [comment]
Let's discuss on slack.

**Comment by bas-rustenburg** [comment]
Seems to work as expected now. Merging.

**Pull request merged**
