### PR TITLE
Calibration API for MonteCarloTitration

### PR DESCRIPTION
**Pull request by bas-rustenburg**
WIP

### CODE REVIEW

**Comment by jchodera** [comment]
@bas-rustenburg : Do you want to clean up the test failures and merge this PR?  We can then debug in parallel.

**Comment by bas-rustenburg** [comment]
@jchodera Ok! On it.

**Comment by bas-rustenburg** [comment]
Cleaned up the code a bit. May have actually cleaned up the bug in the process. Histogram is looking better, may have been related to insufficient sampling of `X` (too few steps)..

**Comment by bas-rustenburg** [comment]
FYI, Not pushed yet.

**Comment by bas-rustenburg** [comment]
Some unexpected passes. Fixing.

**Comment by bas-rustenburg** [comment]
Merging if this passes. @jchodera : let me know if the code structure is unclear.

Basic explanation:
API is now this: `constph.constph.MonteCarloTitration` now has a `calibrate` method. Call this to converge. See `constph/examples/calibration_evaluation.py` for an example of how to use the API. I've been using this to debug.

This method sets up a `constph.calibration.AminoAcidCalibrator` for each of the detected amino acids. It has a `calibrate_till_converged` method to estimate whether SAMS estimates are converged. 
See `constph/examples/calibrator_eval.py` for a debugging script.

Under the hood:
The `AminoAcidCalibrator` sets up a `constph.calibration.CalibrationTitration`, while grabbing system files from  `constph/calibration-systems`.

The `CalibrationTitration` is a subclass of `MonteCarloTitration`, with SAMS implementation.

**Pull request merged**
