### PR TITLE
Trying to get travis to run.

### PR DESCRIPTION
**Pull request by bas-rustenburg**

### CODE REVIEW

**Comment by jchodera** [comment]
Did you remember to switch on the repo in the http://travis-ci.org settings page?

**Comment by bas-rustenburg** [comment]
Yes. Everything is enabled, followed all the steps in the manual. Doesn't seem to be running though.

**Comment by bas-rustenburg** [comment]
https://travis-ci.org/choderalab/openmm-constph/requests  Looks like something is still missing.

**Comment by bas-rustenburg** [comment]
Not sure what missing config means.

**Comment by bas-rustenburg** [comment]
I think there may be a syntax error in my `.travis.yml` file.

**Comment by jchodera** [comment]
https://docs.travis-ci.com/user/travis-lint/

**Comment by bas-rustenburg** [comment]
syntax error: (<unknown>): did not find expected key while parsing a block mapping at line 21 column 3

**Comment by bas-rustenburg** [comment]
No clue what that is supposed to mean... the line number seems to refer to the `matrix` statement.

**Comment by jchodera** [comment]
Check your indentation. `matrix` and `global` begin on different columns.

**Comment by bas-rustenburg** [comment]
That was it. Thanks @jchodera!

**Comment by bas-rustenburg** [comment]
Where does the `_test` environment come from. The boilerplate seems incomplete.

**Comment by jchodera** [comment]
> Where does the _test environment come from? 

`conda build` creates a `_test` environment.

> The boilerplate seems incomplete.

How so?

**Comment by bas-rustenburg** [comment]
> How so?

Sorry, I was referring to the absence of the `_test` environment. I didn't realize that comes from `conda build`. Looks like the problem is in the build step. Will get to fixing it.

**Comment by bas-rustenburg** [comment]
Things are working. Tests are executed (and passing).

**Pull request merged**
